/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { ERC721A__factory } from "./ERC721A__factory";
export { GenericContract__factory } from "./GenericContract__factory";
