/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as genericTokenSol from "./GenericToken.sol";
export type { genericTokenSol };
export type { GenericContract } from "./GenericContract";
export type { GenericStaker } from "./GenericStaker";
