/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export { GenericToken__factory } from "./GenericToken__factory";
export { IGenericToken__factory } from "./IGenericToken__factory";
