/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as genericTokenSol from "./GenericToken.sol";
export { GenericContract__factory } from "./GenericContract__factory";
export { GenericStaker__factory } from "./GenericStaker__factory";
